name: Cross Compile for Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install cross
      run: cargo install cross
    - name: Build binary for aarch64
      run: cross build --target aarch64-unknown-linux-gnu --release
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: trackit-aarch64
        path: target/aarch64-unknown-linux-gnu/release/trackit
